name: Get Unity License Activation File (.alf)
on:
  workflow_dispatch: {} 

jobs:
  get_alf:
    name: Request .alf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get .alf file
        uses: game-ci/unity-request-activation-file@v2.1
        with:
          unityVersion: 6000.2.10f1

      - name: Upload .alf as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_Activation_File
          path: ./*.alf