name: Android CI Build

# 트리거 조건: develop 브랜치에 코드가 Push 될 때마다
on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  buildForAndroid:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      # 저장소의 코드를 서버로 다운로드
      - name: Checkout Code
        uses: actions/checkout@v4

      # 빌드 목적지 폴더 강제 생성
      - name: Create Build Directory
        run: mkdir -p Builds/Android

      # GameCI를 통한 유니티 헤드리스 빌드 실행
      - name: Build with GameCI
        uses: game-ci/unity-builder@v4
        env:
          # 금고에서 꺼내서 GameCI 컨테이너에 주입
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }} # AutoBuilder에서 Environment.GetEnvironmentVariable로 받음
        with:
          targetPlatform: Android
          unityVersion: 6000.2.10f1
          buildMethod: AutoBuilder.BuildAndroidBatch # C# 진입점 타겟팅

      # 빌드 완료된 APK 파일을 GitHub Actions 결과물로 업로드
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AstroCommanders-Android-Build
          path: Builds/Android/*.apk